baseURL = 'https://kisaasi.sirapollokaggwaschools.co.ug/'
languageCode = 'en-us'
title = 'Sir Apollo Kaggwa Primary School Kisaasi'
theme = "saks-theme"

[params]
mainSchool = false
defaultDescription = "Sir Apollo Kaggwa nursery and primary school-Kisaasi is a number one education service provider within Uganda aiming at developing a holistic child throughout the primary level."
    [params.school]
        hm_name = "TWEHEYO SAM"
        hm = "I would like to extend my heartfelt gratitude to each and every one of you for entrusting us with the privilege of educating and nurturing your children. We take this responsibility very seriously and are committed to providing a safe, inclusive, and engaging environment where every child can thrive."
        name = "kisaasi"
        motto = 'We Ignite Excellence in all our pupils.'
        mission = 'To be a leading school in the provision of quality education'
        vision = 'The vision of Sir Apollo Kaggwa Primary School, Kisaasi is to produce devoted learners in academics, moral education and life skills, leadership skills, creativity, and innovation, honest and humble, self-driven with a positive attitude towards quality work.'
        summary1 = 'Welcome to Sir Apollo Kaggwa Primary School Kisaasi, a school that offers holistic and quality primary education in Uganda. Our children excel in National exams with only first grades'
        summary2 = 'Students are given a conducive environment to take part in extra-curricular activities which is part of the syllabus modules enabling them to learn also have their minds refreshed.'
    [params.carousel]
        two = "Offering a broad learning environment"
        three = "We train leaders by embracing smartness"
        four = "Offering the best learning skills to students"
        five = "Welcoming all types of students"
        six = "Interactive teachers that monitor pupils in all activities"
        